repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.37.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        additional_dependencies: [tokenize-rt, attrs]
        args:
          [
            --no-strict-optional,
            --ignore-missing-imports,
            --install-types,
            --no-warn-incomplete-stub,
            --allow-redefinition,
            --implicit-optional,
          ]
        stages: [commit]
  - repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3.8
        args: [--line-length, "80"]
        stages: [commit]
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        stages: [commit]
